export function jsonToGoStructFlexible(
  json: any,
  structName = 'AutoGenerated'
): string {
  const structs: Map<string, string> = new Map();

  if (Array.isArray(json)) {
    if (json.length === 0) return `type ${structName} []interface{}`;
    const merged = mergeObjects(json);
    generateStruct(merged, structName, structs);
    return buildOutput(structs, structName, true);
  } else if (typeof json === 'object' && json !== null) {
    generateStruct(json, structName, structs);
    return buildOutput(structs, structName, false);
  } else {
    throw new Error('Invalid JSON input: must be an object or array');
  }
}

/** Render all collected struct definitions in dependency order */
function buildOutput(
  structs: Map<string, string>,
  rootName: string,
  isArray: boolean
): string {
  const lines: string[] = [];

  // Print nested structs first (all except root), then root last
  for (const [name, body] of structs) {
    if (name !== rootName) {
      lines.push(`type ${name} ${body}\n`);
    }
  }

  const rootBody = structs.get(rootName)!;
  lines.push(
    isArray
      ? `type ${rootName} []${rootBody}`
      : `type ${rootName} ${rootBody}`
  );

  return lines.join('\n');
}

/** Recursively build Go struct body and register all nested structs */
function generateStruct(
  obj: any,
  structName: string,
  structs: Map<string, string>
): void {
  // Avoid re-generating the same struct (e.g., repeated keys)
  if (structs.has(structName)) return;

  let body = `struct {\n`;

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const fieldName = toGoFieldName(key);
    const goType = resolveGoType(value, fieldName, structs);

    body += `\t${fieldName} ${goType} \`json:"${key}"\`\n`;
  }

  body += `}`;

  structs.set(structName, body);
}

/** Resolve the Go type string for a value, recursing for objects/arrays */
function resolveGoType(
  value: any,
  fieldName: string,
  structs: Map<string, string>
): string {
  // ── null ──────────────────────────────────────────────────────────────────
  if (value === null) {
    return 'interface{}';
  }

  // ── Array ─────────────────────────────────────────────────────────────────
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]interface{}';

    const first = value[0];

    if (typeof first === 'object' && first !== null) {
      // Merge ALL array items so every possible field is captured
      const merged = mergeObjects(value.filter((v) => v !== null));
      const nestedName = capitalize(fieldName) + 'Item';
      generateStruct(merged, nestedName, structs);
      return `[]${nestedName}`;
    }

    // Array of primitives — check if all items share the same primitive type
    const elementType = consistentPrimitiveType(value);
    return `[]${elementType}`;
  }

  // ── Nested object ─────────────────────────────────────────────────────────
  if (typeof value === 'object') {
    const nestedName = capitalize(fieldName);
    generateStruct(value, nestedName, structs);
    return nestedName;
  }

  // ── Primitive ─────────────────────────────────────────────────────────────
  return primitiveType(value);
}

/** Merge an array of objects into one representative object */
function mergeObjects(arr: any[]): any {
  return arr.reduce((acc, obj) => {
    if (typeof obj !== 'object' || obj === null) return acc;

    for (const key of Object.keys(obj)) {
      const val = obj[key];

      if (!(key in acc)) {
        // New key — take it as-is
        acc[key] = val;
      } else if (acc[key] === null && val !== null) {
        // Prefer a real value over null
        acc[key] = val;
      } else if (
        typeof acc[key] !== typeof val &&
        typeof val === 'object' &&
        val !== null
      ) {
        // Prefer richer object/array type over a primitive
        acc[key] = val;
      } else if (
        typeof acc[key] === 'object' &&
        !Array.isArray(acc[key]) &&
        typeof val === 'object' &&
        !Array.isArray(val) &&
        val !== null
      ) {
        // Both are objects — merge them recursively so no fields are lost
        acc[key] = mergeObjects([acc[key], val]);
      }
    }
    return acc;
  }, {} as any);
}

/** Return the primitive Go type if all values share one, otherwise interface{} */
function consistentPrimitiveType(arr: any[]): string {
  const types = new Set(arr.map(primitiveType));
  return types.size === 1 ? [...types][0] : 'interface{}';
}

function primitiveType(value: any): string {
  switch (typeof value) {
    case 'string':
      return 'string';
    case 'number':
      return Number.isInteger(value) ? 'int' : 'float64';
    case 'boolean':
      return 'bool';
    default:
      return 'interface{}';
  }
}

function toGoFieldName(key: string): string {
  // Split on non-alphanumeric boundaries, capitalise each segment
  return key
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map(capitalize)
    .join('');
}

function capitalize(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}