export function jsonToDartModel(
  json: any,
  modelName = 'AutoGenerated'
): string {
  const models: Map<string, string> = new Map();

  if (Array.isArray(json)) {
    if (json.length === 0) return `// Empty array — no model generated`;
    const merged = mergeObjects(json);
    generateModel(merged, modelName, models);
  } else if (typeof json === 'object' && json !== null) {
    generateModel(json, modelName, models);
  } else {
    throw new Error('Invalid JSON input: must be an object or array');
  }

  return buildOutput(models);
}

// ─── Output builder ────────────────────────────────────────────────────────────

function buildOutput(models: Map<string, string>): string {
  return [...models.values()].join('\n\n');
}

// ─── Model generator ───────────────────────────────────────────────────────────

function generateModel(
  obj: any,
  modelName: string,
  models: Map<string, string>
): void {
  if (models.has(modelName)) return;

  // Reserve immediately to break circular references
  models.set(modelName, '');

  const fields: string[] = [];
  const constructorParams: string[] = [];
  const fromJsonLines: string[] = [];
  const toJsonLines: string[] = [];

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const dartName = toDartFieldName(key);
    const dartType = resolveType(value, capitalize(dartName), models);

    // ── Field declaration ──────────────────────────────────────────────────
    fields.push(`  ${dartType}? ${dartName};`);

    // ── Constructor param ──────────────────────────────────────────────────
    constructorParams.push(`this.${dartName}`);

    // ── fromJson ───────────────────────────────────────────────────────────
    fromJsonLines.push(...buildFromJsonLines(key, dartName, dartType, value));

    // ── toJson ─────────────────────────────────────────────────────────────
    toJsonLines.push(...buildToJsonLines(key, dartName, dartType, value));
  }

  const ctor = `  ${modelName}({${constructorParams.join(', ')}});`;

  const body = [
    `class ${modelName} {`,
    ...fields,
    ``,
    ctor,
    ``,
    `  ${modelName}.fromJson(Map<String, dynamic> json) {`,
    ...fromJsonLines,
    `  }`,
    ``,
    `  Map<String, dynamic> toJson() {`,
    `    final Map<String, dynamic> data = new Map<String, dynamic>();`,
    ...toJsonLines,
    `    return data;`,
    `  }`,
    `}`,
  ].join('\n');

  models.set(modelName, body);
}

// ─── fromJson line builder ─────────────────────────────────────────────────────

function buildFromJsonLines(
  jsonKey: string,
  dartName: string,
  dartType: string,
  value: any
): string[] {
  // List of model objects
  if (dartType.startsWith('List<')) {
    const innerType = dartType.slice(5, -1); // strip List< >
    const isPrimitive = ['String', 'int', 'double', 'bool', 'dynamic'].includes(innerType);

    if (!isPrimitive) {
      return [
        `    if (json['${jsonKey}'] != null) {`,
        `      ${dartName} = <${innerType}>[];`,
        `      json['${jsonKey}'].forEach((v) {`,
        `        ${dartName}!.add(new ${innerType}.fromJson(v));`,
        `      });`,
        `    }`,
      ];
    } else {
      return [
        `    if (json['${jsonKey}'] != null) {`,
        `      ${dartName} = List<${innerType}>.from(json['${jsonKey}']);`,
        `    }`,
      ];
    }
  }

  // Nested model object
  if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
    return [
      `    ${dartName} = json['${jsonKey}'] != null ? new ${dartType}.fromJson(json['${jsonKey}']) : null;`,
    ];
  }

  // Primitive / null / dynamic
  return [`    ${dartName} = json['${jsonKey}'];`];
}

// ─── toJson line builder ───────────────────────────────────────────────────────

function buildToJsonLines(
  jsonKey: string,
  dartName: string,
  dartType: string,
  value: any
): string[] {
  // List of model objects
  if (dartType.startsWith('List<')) {
    const innerType = dartType.slice(5, -1);
    const isPrimitive = ['String', 'int', 'double', 'bool', 'dynamic'].includes(innerType);

    if (!isPrimitive) {
      return [
        `    if (this.${dartName} != null) {`,
        `      data['${jsonKey}'] = this.${dartName}!.map((v) => v.toJson()).toList();`,
        `    }`,
      ];
    } else {
      return [`    data['${jsonKey}'] = this.${dartName};`];
    }
  }

  // Nested model object
  if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
    return [
      `    if (this.${dartName} != null) {`,
      `      data['${jsonKey}'] = this.${dartName}!.toJson();`,
      `    }`,
    ];
  }

  // Primitive
  return [`    data['${jsonKey}'] = this.${dartName};`];
}

// ─── Type resolver ─────────────────────────────────────────────────────────────

function resolveType(
  value: any,
  fieldName: string,
  models: Map<string, string>
): string {
  if (value === null) return 'dynamic';

  if (Array.isArray(value)) {
    if (value.length === 0) return 'List<dynamic>';

    const nonNull = value.filter((v) => v !== null);
    const first = nonNull[0] ?? value[0];

    if (typeof first === 'object' && first !== null) {
      // "items" → "Item", "orders" → "Order", else append "Item"
      const nestedName = fieldName.endsWith('s')
        ? fieldName.slice(0, -1)
        : fieldName + 'Item';
      const merged = mergeObjects(nonNull.filter((v) => typeof v === 'object'));
      generateModel(merged, nestedName, models);
      return `List<${nestedName}>`;
    }

    const elementType = consistentDartPrimitive(value);
    return `List<${elementType}>`;
  }

  if (typeof value === 'object') {
    generateModel(value, fieldName, models);
    return fieldName;
  }

  return dartPrimitiveType(value);
}

// ─── Merge helpers ─────────────────────────────────────────────────────────────

function mergeObjects(arr: any[]): any {
  return arr.reduce((acc, obj) => {
    if (typeof obj !== 'object' || obj === null) return acc;

    for (const key of Object.keys(obj)) {
      const val = obj[key];

      if (!(key in acc)) {
        acc[key] = val;
      } else if (acc[key] === null && val !== null) {
        acc[key] = val;
      } else if (
        typeof acc[key] !== typeof val &&
        typeof val === 'object' &&
        val !== null
      ) {
        acc[key] = val;
      } else if (
        typeof acc[key] === 'object' &&
        !Array.isArray(acc[key]) &&
        typeof val === 'object' &&
        !Array.isArray(val) &&
        val !== null
      ) {
        acc[key] = mergeObjects([acc[key], val]);
      }
    }
    return acc;
  }, {} as any);
}

// ─── Type helpers ──────────────────────────────────────────────────────────────

function dartPrimitiveType(value: any): string {
  switch (typeof value) {
    case 'string':  return 'String';
    case 'boolean': return 'bool';
    case 'number':  return Number.isInteger(value) ? 'int' : 'double';
    default:        return 'dynamic';
  }
}

function consistentDartPrimitive(arr: any[]): string {
  const types = new Set(arr.map(dartPrimitiveType));
  return types.size === 1 ? [...types][0] : 'dynamic';
}

// ─── Naming helpers ────────────────────────────────────────────────────────────

function toDartFieldName(key: string): string {
  const segments = key.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (segments.length === 0) return '_';
  return (
    segments[0].toLowerCase() +
    segments.slice(1).map(capitalize).join('')
  );
}

function capitalize(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}