export function jsonToPhpArray(
  json: any,
  className = 'AutoGenerated'
): string {
  const classes: Map<string, string> = new Map();

  if (Array.isArray(json)) {
    if (json.length === 0) return `// Empty array — no class generated`;
    const merged = mergeObjects(json);
    generateClass(merged, className, classes);
  } else if (typeof json === 'object' && json !== null) {
    generateClass(json, className, classes);
  } else {
    throw new Error('Invalid JSON input: must be an object or array');
  }

  return buildOutput(classes);
}

// ─── Output builder ────────────────────────────────────────────────────────────

function buildOutput(classes: Map<string, string>): string {
  return `<?php\n\n` + [...classes.values()].join('\n\n');
}

// ─── Class generator ───────────────────────────────────────────────────────────

function generateClass(
  obj: any,
  className: string,
  classes: Map<string, string>
): void {
  if (classes.has(className)) return;

  // Reserve immediately to break circular references
  classes.set(className, '');

  const properties: string[] = [];
  const fromArrayLines: string[] = [];
  const toArrayLines: string[] = [];

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const phpName = toPhpFieldName(key);
    const phpType = resolvePhpType(value, toPascalCase(phpName), classes);
    const docType = toDocType(phpType, value);

    // ── Property declaration ───────────────────────────────────────────────
    properties.push(`    /** @var ${docType} */`);
    properties.push(`    public $${phpName};`);
    properties.push(``);

    // ── fromArray ──────────────────────────────────────────────────────────
    fromArrayLines.push(...buildFromArrayLines(key, phpName, phpType, value));

    // ── toArray ────────────────────────────────────────────────────────────
    toArrayLines.push(...buildToArrayLines(key, phpName, phpType, value));
  }

  const body = [
    `class ${className}`,
    `{`,
    ...properties,
    `    /**`,
    `     * @param array $data`,
    `     * @return static`,
    `     */`,
    `    public static function fromArray(array $data): static`,
    `    {`,
    `        $instance = new static();`,
    ...fromArrayLines,
    `        return $instance;`,
    `    }`,
    ``,
    `    /**`,
    `     * @return array`,
    `     */`,
    `    public function toArray(): array`,
    `    {`,
    `        $data = [];`,
    ...toArrayLines,
    `        return $data;`,
    `    }`,
    `}`,
  ].join('\n');

  classes.set(className, body);
}

// ─── fromArray line builder ────────────────────────────────────────────────────

function buildFromArrayLines(
  jsonKey: string,
  phpName: string,
  phpType: string,
  value: any
): string[] {
  // List of model objects
  if (phpType.startsWith('array<')) {
    const innerType = phpType.slice(6, -1); // strip array< >
    const isPrimitive = ['string', 'int', 'float', 'bool', 'mixed'].includes(innerType);

    if (!isPrimitive) {
      return [
        `        if (isset($data['${jsonKey}']) && is_array($data['${jsonKey}'])) {`,
        `            $instance->${phpName} = [];`,
        `            foreach ($data['${jsonKey}'] as $item) {`,
        `                $instance->${phpName}[] = ${innerType}::fromArray($item);`,
        `            }`,
        `        }`,
      ];
    } else {
      return [
        `        $instance->${phpName} = $data['${jsonKey}'] ?? [];`,
      ];
    }
  }

  // Nested model object
  if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
    return [
      `        if (isset($data['${jsonKey}'])) {`,
      `            $instance->${phpName} = ${phpType}::fromArray($data['${jsonKey}']);`,
      `        }`,
    ];
  }

  // Primitive / null
  return [`        $instance->${phpName} = $data['${jsonKey}'] ?? null;`];
}

// ─── toArray line builder ──────────────────────────────────────────────────────

function buildToArrayLines(
  jsonKey: string,
  phpName: string,
  phpType: string,
  value: any
): string[] {
  // List of model objects
  if (phpType.startsWith('array<')) {
    const innerType = phpType.slice(6, -1);
    const isPrimitive = ['string', 'int', 'float', 'bool', 'mixed'].includes(innerType);

    if (!isPrimitive) {
      return [
        `        if ($this->${phpName} !== null) {`,
        `            $data['${jsonKey}'] = array_map(fn($item) => $item->toArray(), $this->${phpName});`,
        `        }`,
      ];
    } else {
      return [`        $data['${jsonKey}'] = $this->${phpName};`];
    }
  }

  // Nested model object
  if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
    return [
      `        if ($this->${phpName} !== null) {`,
      `            $data['${jsonKey}'] = $this->${phpName}->toArray();`,
      `        }`,
    ];
  }

  // Primitive
  return [`        $data['${jsonKey}'] = $this->${phpName};`];
}

// ─── Type resolver ─────────────────────────────────────────────────────────────

function resolvePhpType(
  value: any,
  fieldName: string,
  classes: Map<string, string>
): string {
  if (value === null) return 'mixed';

  if (Array.isArray(value)) {
    if (value.length === 0) return 'array<mixed>';

    const nonNull = value.filter((v) => v !== null);
    const first = nonNull[0] ?? value[0];

    if (typeof first === 'object' && first !== null) {
      const nestedName = fieldName.endsWith('s')
        ? fieldName.slice(0, -1)
        : fieldName + 'Item';
      const merged = mergeObjects(nonNull.filter((v) => typeof v === 'object'));
      generateClass(merged, nestedName, classes);
      return `array<${nestedName}>`;
    }

    const elementType = consistentPhpPrimitive(value);
    return `array<${elementType}>`;
  }

  if (typeof value === 'object') {
    generateClass(value, fieldName, classes);
    return fieldName;
  }

  return phpPrimitiveType(value);
}

// ─── Doc type helper ───────────────────────────────────────────────────────────

function toDocType(phpType: string, value: any): string {
  if (phpType.startsWith('array<')) {
    const innerType = phpType.slice(6, -1);
    return `${innerType}[]|null`;
  }
  if (value === null) return 'mixed';
  return `${phpType}|null`;
}

// ─── Merge helpers ─────────────────────────────────────────────────────────────

function mergeObjects(arr: any[]): any {
  return arr.reduce((acc, obj) => {
    if (typeof obj !== 'object' || obj === null) return acc;

    for (const key of Object.keys(obj)) {
      const val = obj[key];

      if (!(key in acc)) {
        acc[key] = val;
      } else if (acc[key] === null && val !== null) {
        acc[key] = val;
      } else if (
        typeof acc[key] !== typeof val &&
        typeof val === 'object' &&
        val !== null
      ) {
        acc[key] = val;
      } else if (
        typeof acc[key] === 'object' &&
        !Array.isArray(acc[key]) &&
        typeof val === 'object' &&
        !Array.isArray(val) &&
        val !== null
      ) {
        acc[key] = mergeObjects([acc[key], val]);
      }
    }
    return acc;
  }, {} as any);
}

// ─── Type helpers ──────────────────────────────────────────────────────────────

function phpPrimitiveType(value: any): string {
  switch (typeof value) {
    case 'string':  return 'string';
    case 'boolean': return 'bool';
    case 'number':  return Number.isInteger(value) ? 'int' : 'float';
    default:        return 'mixed';
  }
}

function consistentPhpPrimitive(arr: any[]): string {
  const types = new Set(arr.map(phpPrimitiveType));
  return types.size === 1 ? [...types][0] : 'mixed';
}

// ─── Naming helpers ────────────────────────────────────────────────────────────

/** snake_case / kebab-case / spaces → camelCase PHP property name */
function toPhpFieldName(key: string): string {
  const segments = key.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (segments.length === 0) return '_';
  return (
    segments[0].toLowerCase() +
    segments.slice(1).map(capitalize).join('')
  );
}

/** camelCase → PascalCase for class names */
function toPascalCase(name: string): string {
  return capitalize(name);
}

function capitalize(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}