export function jsonToSwiftModel(
  json: any,
  modelName = 'AutoGenerated'
): string {
  const models: Map<string, string> = new Map();

  if (Array.isArray(json)) {
    if (json.length === 0) return `// Empty array — no model generated`;
    const merged = mergeObjects(json);
    generateModel(merged, modelName, models);
  } else if (typeof json === 'object' && json !== null) {
    generateModel(json, modelName, models);
  } else {
    throw new Error('Invalid JSON input: must be an object or array');
  }

  return buildOutput(models);
}

// ─── Output builder ────────────────────────────────────────────────────────────

/** Emit nested models first, root model last */
function buildOutput(models: Map<string, string>): string {
  return [...models.values()].join('\n\n');
}

// ─── Model generator ───────────────────────────────────────────────────────────

function generateModel(
  obj: any,
  modelName: string,
  models: Map<string, string>
): void {
  if (models.has(modelName)) return;

  // Reserve the name immediately to break circular references
  models.set(modelName, '');

  const properties: string[] = [];
  const codingKeys: string[] = [];
  let needsCodingKeys = false;

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const swiftName = toSwiftFieldName(key);
    const swiftType = resolveSwiftType(value, capitalize(swiftName), models);

    properties.push(`    var ${swiftName}: ${swiftType}`);

    // CodingKeys are needed when the JSON key differs from the Swift name
    codingKeys.push(`        case ${swiftName} = "${key}"`);
    if (swiftName !== key) needsCodingKeys = true;
  }

  // Always emit CodingKeys for explicit mapping (good practice)
  const codingKeysBlock = [
    `    enum CodingKeys: String, CodingKey {`,
    ...codingKeys,
    `    }`,
  ].join('\n');

  const body = [
    `struct ${modelName}: Codable {`,
    ...properties,
    ``,
    codingKeysBlock,
    `}`,
  ].join('\n');

  models.set(modelName, body);
}

// ─── Type resolver ─────────────────────────────────────────────────────────────

function resolveSwiftType(
  value: any,
  fieldName: string,
  models: Map<string, string>
): string {
  // null → optional Any
  if (value === null) return 'Any?';

  // Array
  if (Array.isArray(value)) {
    if (value.length === 0) return '[Any]';

    const first = value[0];

    if (typeof first === 'object' && first !== null) {
      const nestedName = fieldName + 'Item';
      const merged = mergeObjects(value.filter((v) => v !== null && typeof v === 'object'));
      generateModel(merged, nestedName, models);
      return `[${nestedName}]`;
    }

    const elementType = consistentSwiftPrimitive(value);
    return `[${elementType}]`;
  }

  // Nested object
  if (typeof value === 'object') {
    generateModel(value, fieldName, models);
    return fieldName;
  }

  // Primitive
  return swiftPrimitiveType(value);
}

// ─── Merge helpers ─────────────────────────────────────────────────────────────

function mergeObjects(arr: any[]): any {
  return arr.reduce((acc, obj) => {
    if (typeof obj !== 'object' || obj === null) return acc;

    for (const key of Object.keys(obj)) {
      const val = obj[key];

      if (!(key in acc)) {
        acc[key] = val;
      } else if (acc[key] === null && val !== null) {
        acc[key] = val;
      } else if (
        typeof acc[key] !== typeof val &&
        typeof val === 'object' &&
        val !== null
      ) {
        acc[key] = val;
      } else if (
        typeof acc[key] === 'object' &&
        !Array.isArray(acc[key]) &&
        typeof val === 'object' &&
        !Array.isArray(val) &&
        val !== null
      ) {
        acc[key] = mergeObjects([acc[key], val]);
      }
    }
    return acc;
  }, {} as any);
}

// ─── Type helpers ──────────────────────────────────────────────────────────────

function swiftPrimitiveType(value: any): string {
  switch (typeof value) {
    case 'string':  return 'String';
    case 'boolean': return 'Bool';
    case 'number':  return Number.isInteger(value) ? 'Int' : 'Double';
    default:        return 'Any';
  }
}

function consistentSwiftPrimitive(arr: any[]): string {
  const types = new Set(arr.map(swiftPrimitiveType));
  return types.size === 1 ? [...types][0] : 'Any';
}

// ─── Naming helpers ────────────────────────────────────────────────────────────

/**
 * Convert any JSON key to lowerCamelCase Swift identifier.
 * snake_case, kebab-case, spaces, dots — all handled.
 */
function toSwiftFieldName(key: string): string {
  const segments = key.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (segments.length === 0) return '_';
  return (
    segments[0].toLowerCase() +
    segments
      .slice(1)
      .map(capitalize)
      .join('')
  );
}

function capitalize(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}